# web/Vagrantfile

Vagrant.configure("2") do |config|
  config.vm.define "web_server" do |vm|
    vm.vm.box = "ubuntu/focal64"
  
    vm.disksize.size = "20GB"
    vm.vm.network "private_network", ip: "192.168.50.1"
    vm.vm.network "forwarded_port", guest: 22, host: 2001, id: "ssh", auto_correct: true
    vm.vm.network "forwarded_port", guest: 80, host: 80
    vm.vm.network "public_network", bridge: "en1: Wi-Fi (AirPort)"
  
    vm.vm.provider "virtualbox" do |vb|
	  vb.memory = "1024"
      vb.cpus = 1
    end

    vm.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nginx
    
    SHELL
  end
end
